In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from scipy.spatial.distance import pdist, squareform

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

df = pd.read_csv('/kaggle/input/homework-2-dataset/cs455_homework1_report_KhadkaDilleGulley.csv',usecols=[1, 2, 3, 4])
print(df.head()) 

df = df[['category', 'primary_type', 'hp', 'attack']]


# Min-Max Normalization for Numerical Attributes
def min_max_normalization(column):
    return (column - column.min()) / (column.max() - column.min())

df['hp'] = min_max_normalization(df['hp'])
df['attack'] = min_max_normalization(df['attack'])

# Compute Manhattan Distance for Numeric Attributes
numeric_distance = squareform(pdist(df[['hp', 'attack']], metric='cityblock'))

# Normalize numeric distance matrix (avoid division by zero)
if numeric_distance.max() > 0:
    numeric_distance = numeric_distance / numeric_distance.max()


# Compute Distance for Categorical Attributes (Nominal)
def compute_distance_nominal(data):
    distance_matrix = []
    for i in range(len(data)):
        temp = []
        for j in range(len(data)):
            if (data[i] != data[j]):
                difference = 1
            else: 
                difference = 0
            temp.append(difference)
        distance_matrix.append(temp)
    return distance_matrix

# Distance matrices for non-numeric attributes
category_distance = compute_distance_nominal(df['category'].tolist())
type_distance = compute_distance_nominal(df['primary_type'].tolist())

# Convert lists to NumPy arrays
category_distance = np.array(category_distance)
type_distance = np.array(type_distance)

# Normalize numeric distance matrix (already within [0,1])
numeric_distance = numeric_distance / numeric_distance.max()

# Compute final weighted distance matrix (each attribute gets 25%)
final_distance = (0.25 * category_distance) + (0.25 * type_distance) + (0.25 * numeric_distance) + (0.25 * numeric_distance)

# Print all matrices
print("Numeric Distance Matrix:\n", numeric_distance)
print("\nCategory Distance Matrix:\n", category_distance)
print("\nPrimary Type Distance Matrix:\n", type_distance)
print("\nFinal Combined Distance Matrix:\n", final_distance)




    category primary_type   hp  attack
0  legendary        ghost  100      65
1    regular       normal   55      81
2    regular       ground   40      40
3    regular          bug   50      40
4  legendary      psychic   43      29
Numeric Distance Matrix:
 [[0.         0.22553957 0.31654676 ... 0.26019185 0.17422062 0.45059952]
 [0.22553957 0.         0.22913669 ... 0.03465228 0.05995204 0.53800959]
 [0.31654676 0.22913669 0.         ... 0.22901679 0.28908873 0.76714628]
 ...
 [0.26019185 0.03465228 0.22901679 ... 0.         0.08597122 0.5381295 ]
 [0.17422062 0.05995204 0.28908873 ... 0.08597122 0.         0.47805755]
 [0.45059952 0.53800959 0.76714628 ... 0.5381295  0.47805755 0.        ]]

Category Distance Matrix:
 [[0 1 1 ... 1 1 1]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]

Primary Type Distance Matrix:
 [[0 1 1 ... 1 1 1]
 [1 0 1 ... 1 0 1]
 [1 1 0 ... 1 1 1]
 ...
 [1 1 1 ... 0 1 1]
 [1 0 1 ... 1 0 1]
 [1 1 1 ... 1 1 